---
spring_cloud_dataflow_stream_app_starter_uri: "http://bit.ly/Celsius-SR1-stream-applications-kafka-10-maven"
spring_cloud_dataflow_task_app_starter_uri: "http://bit.ly/Clark-GA-task-applications-maven"
