---
spring_cloud_dataflow_server_download_url: "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-server-local/1.3.1.RELEASE/spring-cloud-dataflow-server-local-1.3.1.RELEASE.jar"
spring_cloud_dataflow_server_home: "/solution/spring-cloud-dataflow-server"