---
- name: create directory
  file:
    path: "{{ kafka_home }}"
    mode: "0777"
    state: directory

- name: Download the latest version and unarchive it.
  unarchive:
    src: "{{ kafka_download_url }}"
    dest: "{{ kafka_home }}"
    mode: "0777"
    remote_src: yes
    
- name: find kafka
  find:
    paths: "{{ kafka_home }}"
    file_type: "directory"
    patterns: "kafka*"
    age: "1m"
  register: find_result

- name: should be 1 kafka folder there
  assert:
    that:
    - find_result.matched == 1
    msg: can not find the downloaded kafka  
    
- name: set kafka
  set_fact:
    kafka_version: "{{ find_result.files[0].path | basename }}"   
    
- name: make a symlink to the specific version
  file:
    src: "{{ kafka_home }}/{{ kafka_version }}"
    dest: "{{ kafka_home }}/default"
    mode: "0777"    
    state: link
    
- name: create a script for starting zookeeper-server 
  template:
    src: zookeeper-server-startup.sh.j2
    dest: "{{ kafka_home }}/default/zookeeper-server-startup.sh"
    backup: yes
    mode: 0777
    
- name: create a script for starting kafka-server 
  template:
    src: kafka-server-startup.sh.j2
    dest: "{{ kafka_home }}/default/kafka-server-startup.sh"
    backup: yes
    mode: 0777  