---
- name: wait for server started
  wait_for:
    port: 9393
    delay: 10

- name: register stream apps
  uri:
    url: http://localhost:9393/apps
    method: POST
    user: "{{ spring_cloud_dataflow_username }}"
    password: "{{ spring_cloud_dataflow_password }}"
    body: "uri={{ spring_cloud_dataflow_stream_app_starter_uri }}&force=true"
    status_code: 201
    
- name: register task apps
  uri:
    url: http://localhost:9393/apps
    method: POST
    user: "{{ spring_cloud_dataflow_username }}"
    password: "{{ spring_cloud_dataflow_password }}"    
    body: "uri={{ spring_cloud_dataflow_task_app_starter_uri }}&force=true"
    status_code: 201