---
- name: create directory
  file:
    path: /solution/spring-cloud-dataflow-server/
    state: directory

- name: download 
  get_url:
    url: "{{ download_url }}"
    dest: /solution/spring-cloud-dataflow-server/spring-cloud-dataflow-server-local.jar
    mode: 0777