---
- name: run docker container
  docker_container:
    name: "{{ postgres_docker_container_name }}"
    image: postgres 
    published_ports: 5432:5432
    env:
        POSTGRES_PASSWORD: "{{ postgres_password }}"
    restart_policy: unless-stopped
    state: started